configName: dev

replicaCount: 2

image:
  repository: registry.hub.docker.com/maverickme22/users
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.0.3